### PR TITLE
Adjust dsl of OIDC to reflect assent requirements

### PR DESCRIPTION
**Pull request by schutm**
The OIDC implementation of assent requires the base_url to be set and ignores the different *_url attributes. At favours the returned configuration from the openid_configuration_uri. To not configure some unused attributes they're removed.

### CODE REVIEW

**Review by zachdaniel — APPROVED** [review]
This LGTM, but would like @jimsynz to take a peek first.

**Comment by jimsynz** [comment]
Looks good to me. Would you mind squashing this into a single conventional commit?

**Review by jimsynz — APPROVED** [review]

**Comment by zachdaniel** [comment]
@jimsynz this is going to need to be updated for ash 3.0 anyway, so would you have a chance to update & merge?

**Comment by jimsynz** [comment]
I have manually squashed and merged. Thanks for the contribution @schutm.

**Pull request closed without merging**
